//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddCamera
    {
        public int ACid { get; set; }
        public Nullable<int> ACHierLevel { get; set; }
        public string DeviceID { get; set; }
        public string DeviceType { get; set; }
        public string Cam1 { get; set; }
        public string Cam2 { get; set; }
        public string Cam3 { get; set; }
        public string Cam4 { get; set; }
        public string Cam5 { get; set; }
        public string Cam6 { get; set; }
        public string Cam7 { get; set; }
        public string Cam8 { get; set; }
        public string Cam9 { get; set; }
        public string Cam10 { get; set; }
        public string Cam11 { get; set; }
        public string Cam12 { get; set; }
        public string Cam13 { get; set; }
        public string Cam14 { get; set; }
        public string Cam15 { get; set; }
        public string Cam16 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
