//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class basedata
    {
        public string id { get; set; }
        public int idtype { get; set; }
        public int reference { get; set; }
        public string value { get; set; }

        public string idold { get; set; }
        public string profile { get; set; }
        public string timezone { get; set; }
        public string location { get; set; }
        public string url { get; set; }
        public string description { get; set; }
        public string street { get; set; }
        public string zip { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string vendor { get; set; }
        public string devicemodel { get; set; }
        public string devicetype { get; set; }
        public string branch { get; set; }
        public string branchcode { get; set; }
        public string orginization { get; set; }
        public string softwarever { get; set; }
        public string instdate { get; set; }
        public string serialno { get; set; }
        public string system { get; set; }
        public string agentver { get; set; }
        public string contact1 { get; set; }
        public string contact2 { get; set; }
        public string contact3 { get; set; }
    }
}
