//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class calendar
    {

        [Required]
        [Remote("CalExist", "Customize", ErrorMessage = "Calendar name already exist")]
        [RegularExpression("^[A-Za-z][A-Za-z0-9]*$", ErrorMessage = "Cannot contain empty spaces or Special characters")]
        public string calname { get; set; }
        public string caluserid { get; set; }
        public int type { get; set; }
        [RegularExpression("^[0-9m]{1,2}/[0-9d]{1,2}/[0-9y]{4}$", ErrorMessage = "Enter valid date")]
        public Nullable<System.DateTime> day { get; set; }
        public Nullable<int> dayofweek { get; set; }
        public string period { get; set; }
        public List<string> CalData = new List<string>();
        public List<calendar> Data = new List<calendar>();
        public List<Tuple<string, Int32, DateTime?, Int32?, string>> dataCal = new List<Tuple<string, int, DateTime?, int?, string>>();

    }
}
