//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CashForeCast_Events
    {
        public CashForeCast_Events()
        {
            CalendarEvents = new List<CashForeCast_Events>();
        }
        public string Event_Name { get; set; }
        public string Solar_Day { get; set; }
        public string Lunar_Day { get; set; }
        public Nullable<System.DateTime> Event_Date { get; set; }
        public Nullable<int> Growth_ { get; set; }
        public string CalendarType { get; set; }
        public string EventDate { get; set; }
        public string EventMonth { get; set; }

        public string OldEventName { get; set; }

        public string NextYear { get; set; }
        public List<CashForeCast_Events> CalendarEvents { get; set; }
    }
}
