//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHPHYS_NEW
    {
        public string DEVICEID { get; set; }
        public Nullable<int> DEVICETYPE { get; set; }
        public string REPORTCASSETTTE { get; set; }
    }
}
