//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashcontitem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cashcontitem()
        {
            this.cashstocks = new HashSet<cashstock>();
            this.cashstocks1 = new HashSet<cashstock>();
        }
    
        public string deviceid { get; set; }
        public int containerid { get; set; }
        public int containeritemno { get; set; }
        public int unit { get; set; }
        public int unitsize { get; set; }
        public string currency { get; set; }
        public int currencyexponent { get; set; }
        public int denomination { get; set; }
        public System.DateTime postingdatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cashstock> cashstocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cashstock> cashstocks1 { get; set; }
    }
}
