//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class componentmap
    {
        public int devicetype { get; set; }
        public int componentid { get; set; }
        public int visibleinview { get; set; }
    
        public virtual component component { get; set; }
        public virtual component component1 { get; set; }
        public virtual deviceprofile deviceprofile { get; set; }
        public virtual deviceprofile deviceprofile1 { get; set; }
    }
}
