//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consoleview
    {
        public string viewname { get; set; }
        public int viewtype { get; set; }
        public string extuserid { get; set; }
        public string devices { get; set; }
        public string states { get; set; }
    }
}
