//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE_COMP_TEMP
    {
        public string deviceid { get; set; }
        public System.DateTime timestamp { get; set; }
        public string STATE { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<int> componentid { get; set; }
        public int eventid { get; set; }
        public int prio { get; set; }
    }
}
