//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devicecalendar
    {
        public string deviceid { get; set; }
        public int calendartype { get; set; }
        public string calname { get; set; }
        public string caluserid { get; set; }
    }
}
