//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_
    {
        public string deviceid { get; set; }
        public string hierlevel { get; set; }
        public Nullable<int> devicetype { get; set; }
        public string act_transport { get; set; }
        public string transport1 { get; set; }
        public string transportid1 { get; set; }
        public string transport2 { get; set; }
        public string transportid2 { get; set; }
        public Nullable<int> agenttype { get; set; }
        public string customer_contactid { get; set; }
        public string techn_contactid { get; set; }
        public string supplier_contactid { get; set; }
        public string position { get; set; }
        public string url { get; set; }
        public string multiplexer { get; set; }
        public string outgoingcalls { get; set; }
    
        public virtual deviceprofile deviceprofile { get; set; }
        public virtual deviceprofile deviceprofile1 { get; set; }
        public virtual deviceprofile deviceprofile2 { get; set; }
        public virtual deviceprofile deviceprofile3 { get; set; }
        public virtual deviceprofile deviceprofile4 { get; set; }
        public virtual deviceprofile deviceprofile5 { get; set; }
        public virtual deviceprofile deviceprofile6 { get; set; }
        public virtual deviceprofile deviceprofile7 { get; set; }
        public virtual hierarchy_ hierarchy_ { get; set; }
        public virtual hierarchy_ hierarchy_1 { get; set; }
        public virtual hierarchy_ hierarchy_2 { get; set; }
        public virtual hierarchy_ hierarchy_3 { get; set; }
        public virtual hierarchy_ hierarchy_4 { get; set; }
        public virtual hierarchy_ hierarchy_5 { get; set; }
        public virtual hierarchy_ hierarchy_6 { get; set; }
        public virtual hierarchy_ hierarchy_7 { get; set; }
    }
}
