//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devicefail
    {
        public string deviceid { get; set; }
        public int componentid { get; set; }
        public System.DateTime started { get; set; }
        public Nullable<System.DateTime> ended { get; set; }
        public Nullable<int> eventno { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> compstate { get; set; }
        public Nullable<int> statebit { get; set; }
        public Nullable<int> endeventno { get; set; }
    }
}
