//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Device
    {
        [Required(ErrorMessage = "Device ID Required")]
        public string DeviceID { get; set; }

        [Required(ErrorMessage = "Branch Name Required")]
        public string BranchName { get; set; }

        public Nullable<int> HierLevel { get; set; }

        [RegularExpression(@"^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$", ErrorMessage = "Please Enter approriate IP address")]
        [Required(ErrorMessage = "IP Address Required")]
        public string IP { get; set; }

        [Required(ErrorMessage = "Device Type Required")]
        public string DeviceType { get; set; }

        [Required(ErrorMessage = "Username Required")]
        public string UserID { get; set; }


        [NotMapped]
        [Required(ErrorMessage = "Please Select Hierarchy Level")]
        public string HierName { get; set; }

        public String DevIdOld { get; set; }

        //Reports k lye
        public String time { get; set; }

        public IEnumerable<Device> Devicess { get; set; }
        public List<Device> myDevice { get; set; }

        public List<Hierarchy> hierarchies { get; set; }

        public List<Tuple<String, String, String, String, String>> devicesss = new List<Tuple<String, String, String, String, String>>();

        public bool Selected { get; set; }
        public string CamType { get; set; }


        public List<Tuple<String, String>> data = new List<Tuple<String, String>>();

        public List<String> DevFolder = new List<string>();
        public List<String> hierarchy = new List<string>();
        public List<String> Alldevices = new List<string>();

        //public List<Tuple<String, String>> retList = new List<Tuple<string, string>>();

        public Nullable<bool> Obsolete { get; set; }
        public Nullable<System.DateTime> EJProcessedDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<System.TimeSpan> LastTime { get; set; }

        [Required(ErrorMessage = "Required [By Default 4]")]
        public string LastCardNo { get; set; }

        public string BioInfo { get; set; }

        public Nullable<System.DateTime> BioCmdExecTime { get; set; }
        public string BiosPassword { get; set; }

        public Nullable<bool> BiosUpdated { get; set; }

        public String arry { get; set; }

        //current date & Time k lye
        public String date { get; set; }

        public Nullable<bool> DriverInstalled { get; set; }

        public Nullable<int> PasswordType { get; set; }

        public string Channels { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddCamera> AddCameras { get; set; }
    }
}
