//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmfunction
    {
        public int functionid { get; set; }
        public string description { get; set; }
        public int textnumber { get; set; }
        public int target { get; set; }
        public Nullable<int> executionmode { get; set; }
        public Nullable<int> iconid { get; set; }
        public System.DateTime lastchanged { get; set; }
        public Nullable<int> customizable { get; set; }
    }
}
