//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuplicateDevice
    {
        public string DeviceID { get; set; }
        public string IP { get; set; }
        public System.DateTime LastDate { get; set; }
        public string Description { get; set; }
    }
}
