//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EJTransaction
    {
        public string DeviceID { get; set; }
        public string Trxn_type { get; set; }
        public string Pan { get; set; }
        public string Stan { get; set; }
        public Nullable<System.DateTime> Trxn_date { get; set; }
        public Nullable<System.TimeSpan> Trxn_time { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Trxn_Start { get; set; }
        public Nullable<System.DateTime> Trxn_End { get; set; }
        public string Comment { get; set; }
        public string AccountNo { get; set; }
        public string RRN { get; set; }
        public string Seq_No { get; set; }
    }
}
