//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class @event
    {
        public string deviceid { get; set; }
        public Nullable<int> devicestate { get; set; }
        public System.DateTime timestamp { get; set; }
        public int messageno { get; set; }
        public int eventid { get; set; }
        public string orgmessage { get; set; }
        public Nullable<System.DateTime> servertimestamp { get; set; }
        public Nullable<int> eventno { get; set; }

        //yeh proview wale table se hn jo humare pass nahi
        public int eventcount { get; set; }
        public Nullable<int> eventgroupid { get; set; }


        //yeh Mkhan ne add karae hn
        public string messagetext { get; set; }//
        public string Component { get; set; }//
        public string State { get; set; }//
        public List<String> Ej { get; set; }
        public IEnumerable<Hierarchy> hrar { get; set; }
        public IEnumerable<Device> dev { get; set; }
        public IEnumerable<job> Jobs { get; set; }
        public List<Tuple<string, string, string, int, string, string>> data = new List<Tuple<string, string, string, int, string, string>>();


        //Taha ne pata nahi kyun karae hain
        public List<string> Alview = new List<string>();
        public List<string> Piview = new List<string>();
        public List<string> Chessview = new List<string>();

        //Hassan here
        public List<Tuple<string, string, string, int?, int, string, Tuple<string, string>>> JrData = new List<Tuple<string, string, string, int?, int, string, Tuple<string, string>>>();

        //ye Hassan ne add kiya hai
        public string starttime { get; set; }
        public string endtime { get; set; }

        //Component k lye
        public List<Tuple<string, string, string, int, string>> CompState = new List<Tuple<string, string, string, int, string>>();

        public IEnumerable<TreeNode<Hierarchy, string>> Hiertree { get; set; }
    }
}
