//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventstoreload
    {
        public System.DateTime date110 { get; set; }
        public int hour24 { get; set; }
        public string agmname { get; set; }
        public int count { get; set; }
    }
}
