//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventconversion
    {
        public int messageno { get; set; }
        public int devicetype { get; set; }
        public Nullable<int> eventno { get; set; }
        public string description { get; set; }
    
        public virtual deviceprofile deviceprofile { get; set; }
        public virtual deviceprofile deviceprofile1 { get; set; }
        public virtual deviceprofile deviceprofile2 { get; set; }
        public virtual deviceprofile deviceprofile3 { get; set; }
        public virtual eventbase eventbase { get; set; }
        public virtual eventbase eventbase1 { get; set; }
    }
}
