//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class example
    {
        public int DeviceID { get; set; }
        public System.DateTime Time { get; set; }
        public string CardNo { get; set; }
        public string TransactionID { get; set; }
        public int Trxn_Code { get; set; }
        public string CameraNo { get; set; }
        public string ImagePath { get; set; }
    }
}
