//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hierarchy
    {
        [Required(ErrorMessage = "Hierarchy Name Required")]
        [MaxLength(30)]
        [RegularExpression(@"^[a-zA-Z0-9-]*$", ErrorMessage = "Hierarchy name consits of characters numbers and hiphen  ")]
        public string HierName { get; set; }

        [Required(ErrorMessage = "Hierarchy Level Required")]
        public Nullable<int> Hierlevel { get; set; }

        public string HierId { get; set; }

        public bool Parent { get; set; }

        public bool ParentEdit { get; set; }
        public Nullable<int> OldHierlevel { get; set; }
        public string HierNameEdit { get; set; }
        public string HierlistEdit { get; set; }

        public string Hierlist { get; set; }

        public List<Hierarchy> HierarchyList = new List<Hierarchy>();
        public List<Hierarchy> ChildHier { get; set; }

        public string ParentId { get; set; }

        public List<Device> Devices { get; set; }
    }
}
