//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobcontrol_Temp
    {
        public string jobid { get; set; }
        public string resourceid { get; set; }
        public int commandno { get; set; }
        public System.DateTime timestamp { get; set; }
        public int context { get; set; }
        public Nullable<System.DateTime> jobtsp { get; set; }
    }
}
