//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobschedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jobschedule()
        {
            this.jobs = new HashSet<job>();
            this.jobs1 = new HashSet<job>();
            this.jobs2 = new HashSet<job>();
            this.jobs3 = new HashSet<job>();
        }
    
        public string jobid { get; set; }
        public string description { get; set; }
        public string startit { get; set; }
        public Nullable<int> period { get; set; }
        public Nullable<int> dayofweek { get; set; }
        public string condition { get; set; }
        public int doonce { get; set; }
        public int resultneeded { get; set; }
        public Nullable<int> generic { get; set; }
        public Nullable<int> repeatcount { get; set; }
        public Nullable<int> repeatfreq { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> parallel { get; set; }
        public int conditiontype { get; set; }
        public Nullable<int> sendevent { get; set; }
        public int context { get; set; }
        public string lastmodifieduser { get; set; }
        public int approved { get; set; }
        public string hierlevel { get; set; }
        public Nullable<int> timeout { get; set; }
        public Nullable<int> @internal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job> jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job> jobs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job> jobs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job> jobs3 { get; set; }
    }
}
