//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class lastcomponentevent
    {
        public string deviceid { get; set; }
        public System.DateTime timestamp { get; set; }
        public int messageno { get; set; }
        public string orgmessage { get; set; }
        public System.DateTime servertimestamp { get; set; }
        public int devicestate { get; set; }
        public int eventno { get; set; }
        public Nullable<int> eventcount { get; set; }
        public Nullable<int> eventgroupid { get; set; }
        public int componentid { get; set; }
        public int compstate { get; set; }
        public Nullable<int> compeventcount { get; set; }
        public string description { get; set; }
        public string messagetext { get; set; }
    }
}
