//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineChart_Average
    {
        public System.DateTime PostingDateTime { get; set; }
        public Nullable<int> Average_Hourly { get; set; }
        public Nullable<int> Average_Daily { get; set; }
    }
}
