//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineChartTest
    {
        public string DeviceID { get; set; }
        public System.DateTime PostingDateTime { get; set; }
        public bool ATMDown { get; set; }
        public string Down_Component_Name { get; set; }
    }
}
