//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NDVR
    {
        public int NDid { get; set; }
        public string NDName { get; set; }
        public string NDip { get; set; }
        public string NDusername { get; set; }

        [DataType(DataType.Password)]
        public string NDpassword { get; set; }
        public Nullable<System.DateTime> Ndate { get; set; }
    }
}
