//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class passwordhistory
    {
        public string domain { get; set; }
        public string extuserid { get; set; }
        public System.DateTime changedate { get; set; }
        public string password { get; set; }
    
        public virtual extuser_ extuser_ { get; set; }
        public virtual extuser_ extuser_1 { get; set; }
    }
}
