//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmexecution
    {
        public string deviceid { get; set; }
        public string pmid { get; set; }
        public string pmuserid { get; set; }
        public int originid { get; set; }
        public int step { get; set; }
        public System.DateTime triggertime { get; set; }
        public int triggertype { get; set; }
        public Nullable<int> eventno { get; set; }
        public Nullable<int> reportnumber { get; set; }
        public int onlyonerror { get; set; }
        public int type { get; set; }
        public string jobid { get; set; }
        public string contactid { get; set; }
        public string adress { get; set; }
        public Nullable<int> classification { get; set; }
        public string reporttopic { get; set; }
        public string mt_subject { get; set; }
        public string mt_message { get; set; }
        public string command { get; set; }
        public string vardata { get; set; }
        public Nullable<int> sstpdatalen { get; set; }
        public string sstpdata { get; set; }
    }
}
