//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmresult
    {
        public long counter { get; set; }
        public string pmid { get; set; }
        public string pmuserid { get; set; }
        public int step { get; set; }
        public int triggertype { get; set; }
        public int actiontype { get; set; }
        public System.DateTime timestamp { get; set; }
        public string deviceid { get; set; }
        public int result { get; set; }
        public string comments { get; set; }
        public Nullable<int> state { get; set; }
    }
}
