//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class problem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public problem()
        {
            this.problemdatas = new HashSet<problemdata>();
            this.problemdatas1 = new HashSet<problemdata>();
        }

        public int repnumber { get; set; }
        public string owner { get; set; }
        public string owneruser { get; set; }
        public string id { get; set; }
        public int idtype { get; set; }
        public string reference { get; set; }
        public System.DateTime starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string topic { get; set; }
        public int classif { get; set; }
        public Nullable<int> eventno { get; set; }
        public int status { get; set; }
        public string pmid { get; set; }
        public string pmuserid { get; set; }
        public string externalsystem { get; set; }

        public string remark { get; set; }

        public List<problem> data = new List<problem>();

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<problemdata> problemdatas { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<problemdata> problemdatas1 { get; set; }

    }
}
