//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class pvgroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pvgroup()
        {
            this.pvgroupconditions = new HashSet<pvgroupcondition>();
            this.pvgroupconditions1 = new HashSet<pvgroupcondition>();
        }

        public int groupid { get; set; }
        public string groupname { get; set; }
        public string description { get; set; }
        public Nullable<int> grouptype { get; set; }
        public string criteria { get; set; }
        public string contactid1 { get; set; }
        public string contactid2 { get; set; }
        public string contactid3 { get; set; }
        public string Profile11 { get; set; }
        public string Location11 { get; set; }
        public string Street11 { get; set; }
        public string City11 { get; set; }
        public string Country11 { get; set; }
        public string Longitude11 { get; set; }
        public string Latitude11 { get; set; }
        public string Vendor11 { get; set; }
        public string DevType11 { get; set; }
        public string Orgnization11 { get; set; }
        public string Contact11 { get; set; }
        public string Contact21 { get; set; }
        public string Contact31 { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string Contact3 { get; set; }
        public string PostType { get; set; }
        public List<string> StaticGroups = new List<string>();
        public List<string> DynamicGroups = new List<string>();
        public List<string> Devices = new List<string>();
        public List<Hierarchy> HierarchyList = new List<Hierarchy>();
        public List<Device> DeviceList = new List<Device>();

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pvgroupcondition> pvgroupconditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pvgroupcondition> pvgroupconditions1 { get; set; }
    }
}
