//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pvgroupcondition
    {
        public int groupid { get; set; }
        public int basedatano { get; set; }
        public string criteria { get; set; }
    
        public virtual pvgroup pvgroup { get; set; }
        public virtual pvgroup pvgroup1 { get; set; }
    }
}
