//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pvjournal
    {
        public System.DateTime serverdatetime { get; set; }
        public int issuertype { get; set; }
        public string issuer { get; set; }
        public string pvuser { get; set; }
        public string device { get; set; }
        public int command { get; set; }
        public string adminaction { get; set; }
        public Nullable<int> errorcode { get; set; }
        public Nullable<int> cmdstat { get; set; }
        public string vardata { get; set; }
        public string desktopuser { get; set; }
        public string oldvalue { get; set; }
        public string newvalue { get; set; }
        public Nullable<int> functionid { get; set; }
        public string customer { get; set; }
        public string Operation_Type { get; set; }
        public int id { get; set; }
    }
}
