//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportJob
    {
        public string ReportID { get; set; }
        public string UserID { get; set; }
        public string Description { get; set; }
        public bool active { get; set; }
        public string startit { get; set; }
        public int dayofweek { get; set; }
        public int doonce { get; set; }
        public int period { get; set; }
        public string Recepient { get; set; }
        public string Report_subject { get; set; }
        public string MessageTemplate { get; set; }
        public int commandno { get; set; }
        public string ReportName { get; set; }
        public string deviceid { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
        public string elementid { get; set; }
        public string loginid { get; set; }
        public string categoryid { get; set; }
        public string timenotransaction { get; set; }
        public string approvedstatus { get; set; }
        public string businessgroup { get; set; }
        public string circularoffice { get; set; }
        public string region { get; set; }
        public string businessarea { get; set; }
        public string site { get; set; }
        public string timing { get; set; }
        public string city { get; set; }
        public string manufacturer { get; set; }
        public string tier { get; set; }
        public string exportas { get; set; }
        public string jobid { get; set; }
    }
}
