//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportJobResult
    {
        public string ReportID { get; set; }
        public System.DateTime timestamp { get; set; }
        public string Recepient { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
    }
}
