//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheet1_
    {
        public Nullable<double> F1 { get; set; }
        public Nullable<double> F2 { get; set; }
        public string F3 { get; set; }
        public bool Active { get; set; }
    }
}
