//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusBar
    {
        public string UserID { get; set; }
        public string DeviceID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string FileName { get; set; }
        public string Percentage { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Comment { get; set; }
        public string commandno { get; set; }
    }
}
