//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class stb
    {
        public int type { get; set; }
        public int bit { get; set; }
        public int internalused { get; set; }
        public string color { get; set; }
        public int display { get; set; }
        public int prio { get; set; }
        public int textno { get; set; }
        public int texttype { get; set; }
        public bool disp { get; set; }
        public string data { get; set; }
        public string messagetext { get; set; }

        public List<Tuple<string, string, string, int, string, int>> StbALL = new List<Tuple<string, string, string, int, string, int>>();

        public virtual message0001 message0001 { get; set; }
        public virtual message0001 message00011 { get; set; }
        public virtual message0001 message00012 { get; set; }
    }
}
