//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class UserPermission
    {
        public int ID { get; set; }
        public int Index { get; set; }
        public string Function { get; set; }
        public string Hierarchy { get; set; }
        public string Access { get; set; }

        public Nullable<bool> Licenseon { get; set; }
        public bool Check { get; set; }
        public string Store { get; set; }
        public string Role { get; set; }

        public List<UserPermission> data = new List<UserPermission>();
    }
}
