//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userprofilefunc
    {
        public string category { get; set; }
        public string functionname { get; set; }
        public int action { get; set; }
        public string userprofid { get; set; }
    
        public virtual userprofile userprofile { get; set; }
        public virtual userprofile userprofile1 { get; set; }
    }
}
