//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users_()
        {
            this.extuser_ = new HashSet<extuser_>();
            this.extuser_1 = new HashSet<extuser_>();
        }
    
        public string userid { get; set; }
        public string userprofid { get; set; }
        public string userfunc { get; set; }
        public Nullable<int> userlayout { get; set; }
        public string condition { get; set; }
        public Nullable<int> priority { get; set; }
        public string hierlevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<extuser_> extuser_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<extuser_> extuser_1 { get; set; }
        public virtual hierarchy_ hierarchy_ { get; set; }
        public virtual hierarchy_ hierarchy_1 { get; set; }
        public virtual userprofile userprofile { get; set; }
        public virtual userprofile userprofile1 { get; set; }
    }
}
