//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using SurveilAI.DataContext;
    using System;
    using System.Collections.Generic;

    public partial class UserSecurity
    {
        public string AccountType { get; set; }
        public bool Uview { get; set; }
        public bool Uadd { get; set; }
        public bool Uupd { get; set; }
        public bool Udel { get; set; }
        public bool Iview { get; set; }
        public bool Aview { get; set; }
        public bool Aadd { get; set; }
        public bool Aupd { get; set; }
        public bool Adel { get; set; }
        public bool AAview { get; set; }
        public bool R1view { get; set; }
        public bool R2view { get; set; }
        public bool R3view { get; set; }
        public bool Rview { get; set; }
        public bool SRview { get; set; }
        public bool Hview { get; set; }
        public bool Hadd { get; set; }
        public bool Hupd { get; set; }
        public bool Hdel { get; set; }
        public bool Fview { get; set; }
        public bool EJview { get; set; }
        public bool REJview { get; set; }
        public bool DEJview { get; set; }
        public Nullable<bool> Jview { get; set; }
        public Nullable<bool> JRview { get; set; }
        public Nullable<bool> Mview { get; set; }
        public string Access { get; set; }
        public string Passwordpolicy { get; set; }
        public String Store { get; set; }
        public List<UserSecurity> CheckList { get; set; }

        //public IEnumerable<UserSecurity> usersss { get; set; }
        public IEnumerable<UserSecurity> usersec { get; set; }
        public List<UserCustom> Data = new List<UserCustom>();
    }
}
