//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AlertView
    {
        public string color { get; set; }
        public string DeviceID { get; set; }
        public string DeviceType { get; set; }
        public Nullable<int> HierLevel { get; set; }
        public string state { get; set; }
        public string profile { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> eventno { get; set; }
        public string orgmessage { get; set; }
        public Nullable<int> messageno { get; set; }
        public Nullable<System.DateTime> servertimestamp { get; set; }
        public string address { get; set; }
    }
}
