//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_card_cpture
    {
        public string card_number { get; set; }
        public string sequence_number { get; set; }
        public string machinename { get; set; }
        public string deviceid { get; set; }
        public Nullable<System.DateTime> servertime { get; set; }
        public string orgmessage { get; set; }
        public string status { get; set; }
        public Nullable<int> eventnumber { get; set; }
        public Nullable<System.DateTime> activity_date { get; set; }
    }
}
