//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class V_Current_State
    {
        public string deviceid { get; set; }
        public string color { get; set; }
        public string state { get; set; }

        public List<Tuple<string, string, string>> data = new List<Tuple<string, string, string>>();

    }
}
