//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Downtime_test
    {
        public string state { get; set; }
        public string deviceid { get; set; }
        public Nullable<int> hierlevel { get; set; }
        public string devicetype { get; set; }
    }
}
