//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveilAI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LastImage
    {
        public string deviceid { get; set; }
        public string branchname { get; set; }
        public string IP { get; set; }
        public string DeviceType { get; set; }
        public Nullable<System.DateTime> LastImage { get; set; }
        public Nullable<bool> Connected { get; set; }
        public Nullable<System.DateTime> LastConTime { get; set; }
    }
}
